Repository PyTorchLightning/lightning-Covid19, pull requests merged in 2020-03, with the labels that each got.

#8 basic Info
  LICENSE
  README.md
Labels: documentation

#9 Init environment
  .gitignore
  .travis.yml
  README.md
  lightning_covid19/__init__.py
  requirements.txt
  setup.cfg
  setup.py
  tests/requirements.txt
  tests/test_utilities.py
Labels: tests / CI

#13 allow longer lines
  .pep8speaks.yml
  README.md
  setup.cfg
Labels: tests / CI

#10 Running DenseNet model on covid-chestxray dataset
  .gitignore
  README.md
  data/.gitkeep
  lightning_covid19/model/__init__.py
  lightning_covid19/model/densenet.py
  lightning_covid19/utils.py
  requirements.txt
  run_baseline_densenet.py
Labels: enhancement

#14 linking wiki and experiments from readme
  README.md
Labels: documentation
